-- DROP TABLES IN ORDER OF DEPENDENCIES (CHILD FIRST)
DROP TABLE Asset_Log        CASCADE CONSTRAINTS;
DROP TABLE Payment          CASCADE CONSTRAINTS;
DROP TABLE Review           CASCADE CONSTRAINTS;
DROP TABLE C_Order          CASCADE CONSTRAINTS;

DROP TABLE Inventory        CASCADE CONSTRAINTS;
DROP TABLE Asset            CASCADE CONSTRAINTS;
DROP TABLE Storage          CASCADE CONSTRAINTS;

DROP TABLE Leave            CASCADE CONSTRAINTS;
DROP TABLE Shift            CASCADE CONSTRAINTS;
DROP TABLE Attendance       CASCADE CONSTRAINTS;
DROP TABLE Payslip          CASCADE CONSTRAINTS;

DROP TABLE Ticket           CASCADE CONSTRAINTS;
DROP TABLE Drink            CASCADE CONSTRAINTS;
DROP TABLE Food             CASCADE CONSTRAINTS;
DROP TABLE Product          CASCADE CONSTRAINTS;

DROP TABLE Seat             CASCADE CONSTRAINTS;
DROP TABLE Hall             CASCADE CONSTRAINTS;
DROP TABLE Movie            CASCADE CONSTRAINTS;
DROP TABLE Cinema           CASCADE CONSTRAINTS;
DROP TABLE Franchise        CASCADE CONSTRAINTS;

DROP TABLE Student_Customer        CASCADE CONSTRAINTS;
DROP TABLE Kids_Customer           CASCADE CONSTRAINTS;
DROP TABLE Senior_Citizen_Customer CASCADE CONSTRAINTS;
DROP TABLE Customer                CASCADE CONSTRAINTS;

DROP TABLE Manager         CASCADE CONSTRAINTS;
DROP TABLE Floor_Staff     CASCADE CONSTRAINTS;
DROP TABLE Staff           CASCADE CONSTRAINTS;
DROP TABLE Person          CASCADE CONSTRAINTS;

DROP TABLE Stock_Supplier  CASCADE CONSTRAINTS;
-- Drop relationship tables
DROP TABLE Person_Review CASCADE CONSTRAINTS;
DROP TABLE Person_Franchise CASCADE CONSTRAINTS;
DROP TABLE Person_Payment CASCADE CONSTRAINTS;
DROP TABLE Person_Person CASCADE CONSTRAINTS;
DROP TABLE Person_Order CASCADE CONSTRAINTS;
DROP TABLE Person_Cinema CASCADE CONSTRAINTS;
DROP TABLE Person_Seat CASCADE CONSTRAINTS;
DROP TABLE Seat_Ticket CASCADE CONSTRAINTS;
DROP TABLE Staff_Storage CASCADE CONSTRAINTS;
DROP TABLE Staff_Payslip CASCADE CONSTRAINTS;
DROP TABLE Staff_Shift CASCADE CONSTRAINTS;
DROP TABLE Product_Storage CASCADE CONSTRAINTS;
DROP TABLE Product_Person CASCADE CONSTRAINTS;
DROP TABLE Product_Payment CASCADE CONSTRAINTS;
DROP TABLE Payslip_Shift CASCADE CONSTRAINTS;
DROP TABLE Product_Stock_Supplier CASCADE CONSTRAINTS;
DROP TABLE Product_Order CASCADE CONSTRAINTS;
DROP TABLE Storage_Stock_Supplier CASCADE CONSTRAINTS;
DROP TABLE Cinema_Stock_Supplier CASCADE CONSTRAINTS;
DROP TABLE Staff_Leave CASCADE CONSTRAINTS;
DROP TABLE Staff_Attendance CASCADE CONSTRAINTS;
DROP TABLE Staff_Asset_Log CASCADE CONSTRAINTS;
DROP TABLE Hall_Movie CASCADE CONSTRAINTS;
DROP TABLE Person_Hall CASCADE CONSTRAINTS;
DROP TABLE Cinema_Movie CASCADE CONSTRAINTS;


-- Optionally confirm success
BEGIN
   DBMS_OUTPUT.PUT_LINE('All tables dropped successfully.');
END;
/
